package com.sih.learningplatform.service;
import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import com.sih.learningplatform.dto.*; import com.sih.learningplatform.entity.*; import com.sih.learningplatform.exception.AiServiceException; import com.sih.learningplatform.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.ai.chat.client.ChatClient; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor public class QuizGenerationService { private final ChatClient chatClient; private final LearningMaterialRepository materials; private final QuizRepository quizzes; private final ObjectMapper mapper; @Value("${spring.ai.openai.api-key:mock-openai-key-for-development}") private String key;
 public QuizResponse generateQuiz(QuizGenerateRequest r){var m=materials.save(LearningMaterial.builder().title(r.getTitle()).contentText(r.getDocumentText()).createdAt(LocalDateTime.now()).build());List<QuestionDto> qs;try{qs=isMock()?mock(r):ask(r);}catch(Exception e){qs=mock(r);}if(qs.isEmpty())throw new AiServiceException("AI model failed to generate questions.");var q=Quiz.builder().materialId(m.getId()).createdAt(LocalDateTime.now()).build();qs.forEach(d->q.addQuestion(Question.builder().questionText(d.getQuestionText()).optionA(d.getOptionA()).optionB(d.getOptionB()).optionC(d.getOptionC()).optionD(d.getOptionD()).correctAnswer(d.getCorrectAnswer()).build()));var saved=quizzes.save(q);return QuizResponse.builder().quizId(saved.getId()).materialId(m.getId()).materialTitle(m.getTitle()).totalQuestions(saved.getGeneratedQuestions().size()).questions(saved.getGeneratedQuestions().stream().map(x->QuestionDto.builder().id(x.getId()).questionText(x.getQuestionText()).optionA(x.getOptionA()).optionB(x.getOptionB()).optionC(x.getOptionC()).optionD(x.getOptionD()).correctAnswer(x.getCorrectAnswer()).build()).toList()).createdAt(saved.getCreatedAt()).build();}
 private boolean isMock(){return key==null||key.isBlank()||key.toLowerCase().contains("mock");}
 private List<QuestionDto> ask(QuizGenerateRequest r){String out=chatClient.prompt().system("Generate exactly 3 MCQs. Return only JSON array with questionText, optionA, optionB, optionC, optionD, correctAnswer.").user("Source:\n"+r.getDocumentText()).call().content();try{return mapper.readValue(out.replace("```json","").replace("```",""),new TypeReference<List<QuestionDto>>(){});}catch(Exception e){throw new AiServiceException("AI response could not be parsed",e);}}
 private List<QuestionDto> mock(QuizGenerateRequest r){return List.of(q("What is the main focus of the provided learning material?","Building knowledge of the stated policy or domain","Removing governance controls","Avoiding assessment","Replacing official procedures","optionA"),q("Which approach best supports effective public-sector learning?","Transparent and evidence-based practice","Unverified decisions","Ignoring benchmarks","Avoiding documentation","optionA"),q("What should learners do after reviewing the material?","Apply the concepts and verify understanding","Skip the assessment","Ignore the source","Use unrelated information","optionA"));}
 private QuestionDto q(String t,String a,String b,String c,String d,String k){return QuestionDto.builder().questionText(t).optionA(a).optionB(b).optionC(c).optionD(d).correctAnswer(k).build();}
}
